### ISSUE TITLE
problems with Uptime-Kuma mod

### ISSUE THREAD

**Issue by apperrault** [linuxserver/docker-mods#789] opened 2023-11-20 20:20 UTC
hey all
I am running SWAG via docker compose with an override.  I originally got the docker mod to work, and it was great.  Then I made the mistake of removing a container that had been setup to be monitored and now the docker mod is erroring out and stopping swag when i try and restart it.

here is a link to the swag logs from when I try and start it with the mod enabled
https://pastebin.com/1WdwFLpV

here is the pertinent portions of my compose
 `  swag:
    volumes:
      - ${DOCKERCONFDIR}/organizr/www/db:/organizrlog:ro
    environment:
      - MAXMINDDB_LICENSE_KEY=XXXXXXXXXXXXXXX
      - DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:swag-auto-reload|linuxserver/mods:universal-docker|linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:swag-auto-proxy #|linuxserver/mods:swag-auto-uptime-kuma
      - DISC_HOOK=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - DISC_ME=XXXXXXXXXXXXXXXXXXXXXXXXXXX
      - DOCKER_HOST=tcp://dockerproxy:2375
      - CROWDSEC_API_KEY=XXXXXXXXXXXXXXXXXXXXXXX
      - CROWDSEC_LAPI_URL=http://crowdsec:9091
      - UPTIME_KUMA_URL=http://uptime-kuma:3001/
      - UPTIME_KUMA_USERNAME=admin
      - UPTIME_KUMA_PASSWORD=XXXXXXXXXXXXXXXXXXXXX`
  
Any thoughts on how to fix this?
thanks
app

**Comment by flowcool** [comment] 2023-11-21 17:29
Same here. I just setted up the mod but had uptime kuma running for a while with existing probe.

```
2023-11-21T17:16:58.841510798Z [mod-auto-uptime-kuma] Deleting all monitors that had their containers removed or were disabled
2023-11-21T17:16:58.843282963Z Traceback (most recent call last):
2023-11-21T17:16:58.843526095Z   File "/app/auto-uptime-kuma.py", line 66, in <module>
2023-11-21T17:16:58.848295867Z     swagUptimeKuma.deleteMonitors(monitorsToBeRemoved)
2023-11-21T17:16:58.848475541Z   File "/app/swagUptimeKuma.py", line 105, in deleteMonitors
2023-11-21T17:16:58.848555345Z     self.deleteMonitor(containerName)
2023-11-21T17:16:58.848612092Z   File "/app/swagUptimeKuma.py", line 98, in deleteMonitor
2023-11-21T17:16:58.848659861Z     f"{logPrefix} Deleting monitor {monitorData['id']}:{monitorData['name']}")
2023-11-21T17:16:58.848713808Z                                     ~~~~~~~~~~~^^^^^^
2023-11-21T17:16:58.848918381Z TypeError: 'NoneType' object is not subscriptable
2023-11-21T17:16:59.057629045Z s6-rc: warning: unable to start service init-mod-swag-auto-uptime-kuma-install: command exited 1
``` 

Which makes swag rebooting over and over.

**Comment by flowcool** [comment] 2023-11-26 14:55
A quick "up"... in order to avoid closure. If anyone have any idea..

**Comment by drizuid** [comment] 2023-12-22 15:46
I will note that this mod is not something created or maintained by us.

**Comment by STaRDoGG** [comment] 2024-01-07 18:23
Same issue here. Just added the basic line to several containers;

```
    labels:
      swag.uptime-kuma.enabled: "true"
```

then the environment line to swag to load this mod, and it crashes swag.

```
[mod-auto-uptime-kuma] Creating config directory '/auto-uptime-kuma'
[mod-auto-uptime-kuma] Updating (Delete and Add) monitor 71:Htpc_Tautulli.1.Tf3Lx0Xf95Apq1P5Rep7F1Ukv
[mod-auto-uptime-kuma] Deleting monitor 71:Htpc_Tautulli.1.Tf3Lx0Xf95Apq1P5Rep7F1Ukv
[mod-auto-uptime-kuma] Adding monitor 'Htpc_Tautulli.1.Tf3Lx0Xf95Apq1P5Rep7F1Ukv'
[mod-auto-uptime-kuma] Updating (Delete and Add) monitor 72:Htpc_Overseerr.1.Wkevio8Kgjl9Pdn6R2Ambt90T
[mod-auto-uptime-kuma] Deleting monitor 72:Htpc_Overseerr.1.Wkevio8Kgjl9Pdn6R2Ambt90T
[mod-auto-uptime-kuma] Adding monitor 'Htpc_Overseerr.1.Wkevio8Kgjl9Pdn6R2Ambt90T'
[mod-auto-uptime-kuma] Updating (Delete and Add) monitor 73:Htpc_Ombi.1.V2Q2L70H9T47H2Crm1Sf9Mm9P
[mod-auto-uptime-kuma] Deleting monitor 73:Htpc_Ombi.1.V2Q2L70H9T47H2Crm1Sf9Mm9P
[mod-auto-uptime-kuma] Adding monitor 'Htpc_Ombi.1.V2Q2L70H9T47H2Crm1Sf9Mm9P'
[mod-auto-uptime-kuma] Updating (Delete and Add) monitor 74:Htpc_Plex.1.Kkohvpqwr6Dbzd2Lxroez9U7C
[mod-auto-uptime-kuma] Deleting monitor 74:Htpc_Plex.1.Kkohvpqwr6Dbzd2Lxroez9U7C
[mod-auto-uptime-kuma] Adding monitor 'Htpc_Plex.1.Kkohvpqwr6Dbzd2Lxroez9U7C'
[mod-auto-uptime-kuma] Updating (Delete and Add) monitor 75:Htpc_Bazarr.1.Y4U8Jqn7Ftk1Gvu3T1Joz1Pkz
[mod-auto-uptime-kuma] Deleting monitor 75:Htpc_Bazarr.1.Y4U8Jqn7Ftk1Gvu3T1Joz1Pkz
[mod-auto-uptime-kuma] Adding monitor 'Htpc_Bazarr.1.Y4U8Jqn7Ftk1Gvu3T1Joz1Pkz'
[mod-auto-uptime-kuma] Updating (Delete and Add) monitor 76:Htpc_Sonarr.1.65Johgwt2Brnx4R1Nfs3Qnrhd
[mod-auto-uptime-kuma] Deleting monitor 76:Htpc_Sonarr.1.65Johgwt2Brnx4R1Nfs3Qnrhd
[mod-auto-uptime-kuma] Adding monitor 'Htpc_Sonarr.1.65Johgwt2Brnx4R1Nfs3Qnrhd'
[mod-auto-uptime-kuma] Updating (Delete and Add) monitor 77:Htpc_Radarr.1.Qko1Uxh0G4Lmmwohqn9Qtae5X
[mod-auto-uptime-kuma] Deleting monitor 77:Htpc_Radarr.1.Qko1Uxh0G4Lmmwohqn9Qtae5X
[mod-auto-uptime-kuma] Adding monitor 'Htpc_Radarr.1.Qko1Uxh0G4Lmmwohqn9Qtae5X'
[mod-auto-uptime-kuma] Deleting all monitors that had their containers removed or were disabled
Traceback (most recent call last):
  File "/app/auto-uptime-kuma.py", line 66, in <module>
    swagUptimeKuma.deleteMonitors(monitorsToBeRemoved)
  File "/app/swagUptimeKuma.py", line 105, in deleteMonitors
    self.deleteMonitor(containerName)
  File "/app/swagUptimeKuma.py", line 98, in deleteMonitor
    f"{logPrefix} Deleting monitor {monitorData['id']}:{monitorData['name']}")
                                    ~~~~~~~~~~~^^^^^^
TypeError: 'NoneType' object is not subscriptable
s6-rc: warning: unable to start service init-mod-swag-auto-uptime-kuma-install: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

I know nothing about python or I'd maybe take a peek at the code.

**Comment by YouveGotMeowxy** [comment] 2024-01-08 05:08
I just got this error:

```
Building wheels for collected packages: uptime-kuma-api
  Building wheel for uptime-kuma-api (setup.py): started
  Building wheel for uptime-kuma-api (setup.py): finished with status 'done'
  Created wheel for uptime-kuma-api: filename=uptime_kuma_api-1.2.1-py3-none-any.whl size=46567 sha256=bd5a8a52e119e7222ff2a7ab9e284ea8ab76c171d29ced51518fb93eecf93d82
  Stored in directory: /root/.cache/pip/wheels/28/a3/72/c8b9df434aeac0f332b30e0051dfa90f1a93fcccce1a2f6783
Successfully built uptime-kuma-api
Installing collected packages: websocket-client, h11, bidict, wsproto, docker, simple-websocket, python-engineio, python-socketio, uptime-kuma-api
Successfully installed bidict-0.22.1 docker-7.0.0 h11-0.14.0 python-engineio-4.8.2 python-socketio-5.11.0 simple-websocket-1.0.0 uptime-kuma-api-1.2.1 websocket-client-1.7.0 wsproto-1.2.0
Applying the maxmind mod...
[mod-auto-uptime-kuma] Executing SWAG auto-uptime-kuma mod
sed: unmatched '|'
Applied the maxmind mod
Traceback (most recent call last):
  File "/app/auto-uptime-kuma.py", line 62, in <module>
[mod-auto-uptime-kuma] Creating config directory '/auto-uptime-kuma'
[mod-auto-uptime-kuma] Adding monitor 'Crowdsec'
    addOrUpdateMonitors(domainName, swagContainers)
  File "/app/auto-uptime-kuma.py", line 31, in addOrUpdateMonitors
    swagUptimeKuma.addMonitor(containerName, domainName, monitorData)
  File "/app/swagUptimeKuma.py", line 83, in addMonitor
    monitor = self._api.add_monitor(**monitorData)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/uptime_kuma_api/api.py", line 1472, in add_monitor
    return self._call('add', data)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/uptime_kuma_api/api.py", line 550, in _call
    raise UptimeKumaException(r.get("msg"))
uptime_kuma_api.exceptions.UptimeKumaException: insert into `monitor` (`accepted_statuscodes_json`, `auth_method`, `body`, `database_connection_string`, `description`, `dns_resolve_server`, `dns_resolve_type`, `expiry_notification`, `headers`, `hostname`, `http_body_encoding`, `ignore_tls`, `interval`, `kafka_producer_brokers`, `kafka_producer_sasl_options`, `maxredirects`, `maxretries`, `method`, `mqtt_password`, `mqtt_success_message`, `mqtt_topic`, `mqtt_username`, `name`, `packet_size`, `parent`, `port`, `proxy_id`, `resend_interval`, `retry_interval`, `timeout`, `type`, `upside_down`, `url`, `user_id`) values ('["200-299"]', '', NULL, NULL, 'Crowd-Sourced Firewall-ish', '1.1.1.1', 'A', false, NULL, NULL, 'json', false, 60, NULL, NULL, 10, 1, 'GET', '', '', '', '', 'Crowdsec', 56, 'SECURITY', NULL, NULL, 0, 60, 48, 'http', false, 'https://crowdsec.domain.com', 1) - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
s6-rc: warning: unable to start service init-mod-swag-auto-uptime-kuma-install: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

Seems like this mod could use some love. :)

**Comment by YouveGotMeowxy** [comment] 2024-02-08 00:12
Keep alive

**Comment by Draky50110** [comment] 2024-02-28 21:13
Here : problem with enabling a container and restarting SWAG.

Log : 

`[mod-auto-uptime-kuma] Executing SWAG auto-uptime-kuma mod
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/lsiopy/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.11/http/client.py", line 1293, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1052, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 990, in send
    self.connect()
  File "/lsiopy/lib/python3.11/site-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/lsiopy/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/lsiopy/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.11/http/client.py", line 1293, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1052, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 990, in send
    self.connect()
  File "/lsiopy/lib/python3.11/site-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/docker/api/client.py", line 213, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/docker/utils/decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/docker/api/client.py", line 236, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/auto-uptime-kuma.py", line 55, in <module>
    swagDocker = SwagDocker("swag.uptime-kuma")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/swagDocker.py", line 15, in __init__
    self.client = docker.from_env()
                  ^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/docker/client.py", line 94, in from_env
    return cls(
           ^^^^
  File "/lsiopy/lib/python3.11/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/docker/api/client.py", line 220, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
s6-rc: warning: unable to start service init-mod-swag-auto-uptime-kuma-install: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.`

**Comment by labmonkey** [comment] 2024-03-12 21:31
Hello everyone. Sorry for not looking into this issue but I had some other duties. I will work on fix and give you an update soon.

**Comment by labmonkey** [comment] 2024-03-12 23:31
> Here : problem with enabling a container and restarting SWAG.
> 
> Log :
> 
> `[mod-auto-uptime-kuma] Executing SWAG auto-uptime-kuma mod Traceback (most recent call last): File "/lsiopy/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen response = self._make_request( ^^^^^^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/urllib3/connectionpool.py", line 497, in _make_request conn.request( File "/lsiopy/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request self.endheaders() File "/usr/lib/python3.11/http/client.py", line 1293, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/lib/python3.11/http/client.py", line 1052, in _send_output self.send(msg) File "/usr/lib/python3.11/http/client.py", line 990, in send self.connect() File "/lsiopy/lib/python3.11/site-packages/docker/transport/unixconn.py", line 27, in connect sock.connect(self.unix_socket) FileNotFoundError: [Errno 2] No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/lsiopy/lib/python3.11/site-packages/requests/adapters.py", line 486, in send resp = conn.urlopen( ^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/urllib3/connectionpool.py", line 845, in urlopen retries = retries.increment( ^^^^^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/urllib3/util/retry.py", line 470, in increment raise reraise(type(error), error, _stacktrace) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/urllib3/util/util.py", line 38, in reraise raise value.with_traceback(tb) File "/lsiopy/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen response = self._make_request( ^^^^^^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/urllib3/connectionpool.py", line 497, in _make_request conn.request( File "/lsiopy/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request self.endheaders() File "/usr/lib/python3.11/http/client.py", line 1293, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/lib/python3.11/http/client.py", line 1052, in _send_output self.send(msg) File "/usr/lib/python3.11/http/client.py", line 990, in send self.connect() File "/lsiopy/lib/python3.11/site-packages/docker/transport/unixconn.py", line 27, in connect sock.connect(self.unix_socket) urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/lsiopy/lib/python3.11/site-packages/docker/api/client.py", line 213, in _retrieve_server_version return self.version(api_version=False)["ApiVersion"] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/docker/api/daemon.py", line 181, in version return self._result(self._get(url), json=True) ^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/docker/utils/decorators.py", line 44, in inner return f(self, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/docker/api/client.py", line 236, in _get return self.get(url, **self._set_request_timeout(kwargs)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/requests/sessions.py", line 602, in get return self.request("GET", url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/requests/adapters.py", line 501, in send raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/app/auto-uptime-kuma.py", line 55, in swagDocker = SwagDocker("swag.uptime-kuma") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/swagDocker.py", line 15, in **init** self.client = docker.from_env() ^^^^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/docker/client.py", line 94, in from_env return cls( ^^^^ File "/lsiopy/lib/python3.11/site-packages/docker/client.py", line 45, in **init** self.api = APIClient(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/docker/api/client.py", line 197, in **init** self._version = self._retrieve_server_version() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lsiopy/lib/python3.11/site-packages/docker/api/client.py", line 220, in _retrieve_server_version raise DockerException( docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory')) s6-rc: warning: unable to start service init-mod-swag-auto-uptime-kuma-install: command exited 1 /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information. /run/s6/basedir/scripts/rc.init: fatal: stopping the container.`

I should mention in documentation that this works similar to the swag-auto-proxy https://github.com/linuxserver/docker-mods/tree/swag-auto-proxy and as you see there in requirements:
- This mod needs the [universal-docker mod](https://github.com/linuxserver/docker-mods/tree/universal-docker) installed and set up with either mapping docker.sock or setting the environment variable DOCKER_HOST=remoteaddress.
- Other containers to be auto-detected and reverse proxied should be in the same [user defined bridge network](https://docs.linuxserver.io/general/swag#docker-networking) as SWAG.

Please follow that and it will work

**Comment by labmonkey** [comment] 2024-03-12 23:52
> I just got this error:
> 
> ```
> Building wheels for collected packages: uptime-kuma-api
>   Building wheel for uptime-kuma-api (setup.py): started
>   Building wheel for uptime-kuma-api (setup.py): finished with status 'done'
>   Created wheel for uptime-kuma-api: filename=uptime_kuma_api-1.2.1-py3-none-any.whl size=46567 sha256=bd5a8a52e119e7222ff2a7ab9e284ea8ab76c171d29ced51518fb93eecf93d82
>   Stored in directory: /root/.cache/pip/wheels/28/a3/72/c8b9df434aeac0f332b30e0051dfa90f1a93fcccce1a2f6783
> Successfully built uptime-kuma-api
> Installing collected packages: websocket-client, h11, bidict, wsproto, docker, simple-websocket, python-engineio, python-socketio, uptime-kuma-api
> Successfully installed bidict-0.22.1 docker-7.0.0 h11-0.14.0 python-engineio-4.8.2 python-socketio-5.11.0 simple-websocket-1.0.0 uptime-kuma-api-1.2.1 websocket-client-1.7.0 wsproto-1.2.0
> Applying the maxmind mod...
> [mod-auto-uptime-kuma] Executing SWAG auto-uptime-kuma mod
> sed: unmatched '|'
> Applied the maxmind mod
> Traceback (most recent call last):
>   File "/app/auto-uptime-kuma.py", line 62, in <module>
> [mod-auto-uptime-kuma] Creating config directory '/auto-uptime-kuma'
> [mod-auto-uptime-kuma] Adding monitor 'Crowdsec'
>     addOrUpdateMonitors(domainName, swagContainers)
>   File "/app/auto-uptime-kuma.py", line 31, in addOrUpdateMonitors
>     swagUptimeKuma.addMonitor(containerName, domainName, monitorData)
>   File "/app/swagUptimeKuma.py", line 83, in addMonitor
>     monitor = self._api.add_monitor(**monitorData)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/lsiopy/lib/python3.11/site-packages/uptime_kuma_api/api.py", line 1472, in add_monitor
>     return self._call('add', data)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/lsiopy/lib/python3.11/site-packages/uptime_kuma_api/api.py", line 550, in _call
>     raise UptimeKumaException(r.get("msg"))
> uptime_kuma_api.exceptions.UptimeKumaException: insert into `monitor` (`accepted_statuscodes_json`, `auth_method`, `body`, `database_connection_string`, `description`, `dns_resolve_server`, `dns_resolve_type`, `expiry_notification`, `headers`, `hostname`, `http_body_encoding`, `ignore_tls`, `interval`, `kafka_producer_brokers`, `kafka_producer_sasl_options`, `maxredirects`, `maxretries`, `method`, `mqtt_password`, `mqtt_success_message`, `mqtt_topic`, `mqtt_username`, `name`, `packet_size`, `parent`, `port`, `proxy_id`, `resend_interval`, `retry_interval`, `timeout`, `type`, `upside_down`, `url`, `user_id`) values ('["200-299"]', '', NULL, NULL, 'Crowd-Sourced Firewall-ish', '1.1.1.1', 'A', false, NULL, NULL, 'json', false, 60, NULL, NULL, 10, 1, 'GET', '', '', '', '', 'Crowdsec', 56, 'SECURITY', NULL, NULL, 0, 60, 48, 'http', false, 'https://crowdsec.domain.com', 1) - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
> s6-rc: warning: unable to start service init-mod-swag-auto-uptime-kuma-install: command exited 1
> /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
> /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
> ```
> 
> My labels:
> 
> ```
>     labels:
>       swag.uptime-kuma.enabled: "true"
>       swag.uptime-kuma.monitor.name: "Crowdsec"
>       swag.uptime-kuma.monitor.url: "https://crowdsec.domain.com"
>       swag.uptime-kuma.monitor.description: "Crowd-Sourced Firewall-ish"
>       swag.uptime-kuma.monitor.parent: "SECURITY"
> ```
> 
> Seems like this mod could use some love. :)

It is because you are configuring a monitor group as well with `swag.uptime-kuma.monitor.parent: "SECURITY"`. This is not supported now but I will try to add a simple automatic group creation. By simple I mean that groups act similar to monitors and have their own set of extra settings but this mod is about configuring monitors for containers so I can just automatically create a group with that name and default settings.

**Comment by Draky50110** [comment] 2024-03-12 23:52
Better result but still problem :

[mod-auto-uptime-kuma] Executing SWAG auto-uptime-kuma mod
[mod-auto-uptime-kuma] Monitor 3:Transmission is unchanged, skipping...
[mod-auto-uptime-kuma] Monitor 4:Navidrome-Navidrome-1 is unchanged, skipping...
[mod-auto-uptime-kuma] Deleting all monitors that had their containers removed or were disabled
Traceback (most recent call last):
  File "/app/auto-uptime-kuma.py", line 66, in <module>
    swagUptimeKuma.deleteMonitors(monitorsToBeRemoved)
  File "/app/swagUptimeKuma.py", line 105, in deleteMonitors
    self.deleteMonitor(containerName)
  File "/app/swagUptimeKuma.py", line 98, in deleteMonitor
    f"{logPrefix} Deleting monitor {monitorData['id']}:{monitorData['name']}")
                                    ~~~~~~~~~~~^^^^^^
TypeError: 'NoneType' object is not subscriptable
s6-rc: warning: unable to start service init-mod-swag-auto-uptime-kuma-install: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.

**Comment by labmonkey** [comment] 2024-03-12 23:54
Regarding the initial issue
```
2023-11-21T17:16:58.848612092Z   File "/app/swagUptimeKuma.py", line 98, in deleteMonitor
2023-11-21T17:16:58.848659861Z     f"{logPrefix} Deleting monitor {monitorData['id']}:{monitorData['name']}")
```
This is very weird because it seems it can find the monitor in the Uptime Kuma itself but then the monitor is lacking data for some reason? Having hard time reproducing this so I might need an extra evening.

**Comment by labmonkey** [comment] 2024-03-18 13:58
I've managed to reproduce this bug by creating a monitor manually in Uptime Kuma which caused the mod to crash. Now this mod does not manage monitors that it did not create itself. I hope that was the issue.

**Comment by flowcool** [comment] 2024-03-18 15:40
> I've managed to reproduce this bug by creating a monitor manually in Uptime Kuma which caused the mod to crash. Now this mod does not manage monitors that it did not create itself (which it was supposed to do). I hope that was the issue.

Yep you got it. Uptimekuma have to be empty to be able to work. That's a bit of a shame to not be able to have other monitoring in place.

**Comment by labmonkey** [comment] 2024-03-18 16:27
> > I've managed to reproduce this bug by creating a monitor manually in Uptime Kuma which caused the mod to crash. Now this mod does not manage monitors that it did not create itself (which it was supposed to do). I hope that was the issue.
> 
> Yep you got it. Uptimekuma have to be empty to be able to work. That's a bit of a shame to not be able to have other monitoring in place.

Well that's no longer the case now! Feel free to test new version before it gets merged: `DOCKER_MODS: ghcr.io/linuxserver/mods:pull_request_866`

**Comment by Draky50110** [comment] 2024-03-18 21:28
Worked for me.

**Comment by YouveGotMeowxy** [comment] 2024-04-21 05:46
@labmonkey working great for me! TY

**Closed** 2024-04-21 14:38 UTC
Labels: help wanted, no-issue-activity
