### ISSUE TITLE
Maxmind mod not working on root domain?

### ISSUE THREAD

**Issue by schumi2004** [linuxserver/docker-mods#611] opened 2023-03-29 19:28 UTC
Is it possible that the instructions for Maxmind mod don't include instructions to geo block on root domain?
I also have crowdsec running and received alot of attempts from countries that i have not allowed/blocked, i actually only have my home country allowed and nothing else, still i see connection attempts from all over the world.

It seems to be working for subdomain/subfolder level but not on root atleast that is what i think since I did not see instructions to include it there?

**Comment by aptalca** [comment] 2023-05-21 02:35
It works for any server block you include the arguments in. The server block for the naked domain is in site-confs/default.conf

Closing as it's not a bug. If you need help with geoblock settings, you can ask in our discord or discourse

**Closed by aptalca** 2023-05-21 02:35 UTC
