### ISSUE TITLE
Docker-in-Docker and ffmpeg script with cuda capabilities

### ISSUE THREAD

**Issue by Jorman** [linuxserver/docker-mods#898] opened 2024-05-14 19:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Name of mod

Docker-in-Docker

### Name of base container

ghcr.io/linuxserver/radarr

### Current Behavior

When the script run this's the error
```
05/14/2024
08:50:10 PM
[Error] Multimedia_Telegram_Bot.sh: docker: Error response from daemon: unknown or invalid runtime name: nvidia. 
05/14/2024
08:50:10 PM
[Error] Multimedia_Telegram_Bot.sh: See 'docker run --help'. 
```

### Expected Behavior

Compress the file without error

### Steps To Reproduce

I run the radarr with this docker
But when the script start this's the code that run
```
					docker run --rm \
						--runtime=nvidia \
						-v /Sharing:/Sharing \
						linuxserver/ffmpeg \
						-hwaccel nvdec \
						-i "$radarr_moviefile_path" \
						-preset fast \
						-map 0:v -map 0:a? -c:a libfdk_aac -b:a 128k \
						-c:v:0 hevc_nvenc -vf "scale=-1:720" \
						-b:v ${bitrate_video}k -maxrate:v ${bitrate_video}k -bufsize $(( $bitrate_video / 2 * 125 / 100))k \
						"$new_file"
```
Before using the script I tested it outside the Docker-in-Docker and all is working.

After some search, I double-checked that the nvidia runtime is configured and seems all ok
```
nvidia-ctk runtime configure --runtime=docker
INFO[0000] Loading config from /etc/docker/daemon.json
INFO[0000] Wrote updated config to /etc/docker/daemon.json
INFO[0000] It is recommended that docker daemon be restarted.
```
```
cat /etc/docker/daemon.json
{
    "data-root": "/var/lib/docker",
    "runtimes": {
        "nvidia": {
            "args": [],
            "path": "nvidia-container-runtime"
        }
    }
}
```

Any idea?

### Environment

```markdown
- OS: Openmediavault 7 - based on debian 12
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
    radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: t-radarr
        privileged: true
        environment:
            - DOCKER_MODS=linuxserver/mods:universal-docker-in-docker
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_APPDATA}/t-radarr:/config
            - ${SHARING}:/Sharing
            - ${UTILITIES}/scripts:/scripts
        ports:
            - 17878:7878
        restart: unless-stopped
```

### Container logs

```bash
05/14/2024
08:50:10 PM
[Error] Multimedia_Telegram_Bot.sh: docker: Error response from daemon: unknown or invalid runtime name: nvidia. 
05/14/2024
08:50:10 PM
[Error] Multimedia_Telegram_Bot.sh: See 'docker run --help'.
```

**Comment by Jorman** [comment] 2024-05-14 20:53
Ah, right, I hadn't thought about that!
But so I have to follow the whole procedure? -> https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
Or do you have an alternative tip or advice for this?

**Comment by j0nnymoe** [comment] 2024-05-14 21:03
Yep you need to install their container toolkit.

**Comment by Jorman** [comment] 2024-05-15 10:21
Ok, this start to be "complicated" for my use, so I make some search and I found a docker with ffmpeg and nvidia-cuda
https://github.com/aperim/docker-nvidia-cuda-ffmpeg
I changed the docker mod to docker instead docker-in-docker and is working like expected

I only have a weird problem
Radarr start with mounted volume `${SHARING}:/Sharing` where the global env point to `SHARING=/srv/dev-disk-by-uuid-ecc70552-d999-49f3-b5e4-9a0250e1c559/Sharing`
So inside Radarr docker I can see /Sharing and is ok, but when Radarr call the script
```
docker run --rm \
	--gpus=all -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all \
	-v /Sharing:/Sharing \
	ghcr.io/aperim/nvidia-cuda-ffmpeg:latest \
	-hwaccel nvdec \
	-i "$radarr_moviefile_path" \
	-preset fast \
	-map 0:v -map 0:a? -c:a libfdk_aac -b:a 128k \
	-c:v:0 hevc_nvenc -vf "scale=-1:720" \
	-b:v ${bitrate_video}k -maxrate:v ${bitrate_video}k -bufsize $(( $bitrate_video / 2 * 125 / 100))k \
	"$new_file"
```
the /Sharing is mounted but is not working is an empty directory, but if I pass the
`-v /srv/dev-disk-by-uuid-ecc70552-d999-49f3-b5e4-9a0250e1c559/Sharing:/Sharing \`
is working
How come I have to map this way and I can't map /Sharing which is already mapped inside the docker?

**Comment by aptalca** [comment] 2024-05-15 12:50
1. If you switched to `universal-docker` instead of `universal-docker-in-docker`, then you didn't have to switch to that other ffmpeg container. Because now you're running that container in the host, not inside radarr.
2. You need to use the host path because now your ffmpeg container is running on the host, not inside radarr

**Comment by Jorman** [comment] 2024-05-15 13:16
Ok, now make more sense to me, thanks!
So if I use docker in docker I've the advantage to have already mapped all the volumes but maybe I can't have access to nvidia gpu, I can try to add
```
        deploy:
          resources:
            reservations:
              devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
```
to the docker-compose of Radarr but I don't know if is working, I'll made a little test.
But if I switch to docker, I've also to pass the global.env file to my docker run inside the script but for sure I'll be able to use the gpu from the host
What do you think is the best way?

**Comment by Jorman** [comment] 2024-05-15 14:38
Ok, test made with `universal-docker-in-docker` I don't have access to nvidia gpu, so I need to switch to `universal-docker`
But I still have a "problem" with my docker run
```
docker run --rm --env-file /docker-config/compose/global.env \
	--gpus=all -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all \
	-v ${SHARING}:/Sharing \
	ghcr.io/aperim/nvidia-cuda-ffmpeg:latest \
	-hwaccel nvdec \
	-i "$radarr_moviefile_path" \
	-preset fast \
	-map 0:v -map 0:a? -c:a libfdk_aac -b:a 128k \
	-c:v:0 hevc_nvenc -vf "scale=-1:720" \
	-b:v ${bitrate_video}k -maxrate:v ${bitrate_video}k -bufsize $(( $bitrate_video / 2 * 125 / 100))k \
	"$new_name"
```
The volume does not mount with the variable, I replace it with the actual path, since it runs on the host, it works.
It seems that the `env` file is not being read
`docker: open /docker-config/compose/global.env: no such file or directory.`
Surely I am doing something wrong, the host volume is mounted while the host file is not read, what am I missing?

**Comment by aptalca** [comment] 2024-05-15 14:52
This is really outside of our support. It looks like both mods are technically working for you in terms of creating containers and all that. If you're using the `universal-docker` mod, the docker arguments need to reference things from the host's perspective, as the container is being created via the host's docker service.

Closing as it's not a bug.

If you need further help, you can drop by our discord.

**Closed by aptalca** 2024-05-15 14:52 UTC
